clone_depth: 5

environment:
  access_token:
    secure: tFQkbFAxE8tVh+D8CH5Qr4Nhz/ENYFeBnu8uREJwwwzMdGTcH+GTIpIQyzxDSvWa

install:
  - node --version
  - npm --version
  - npm cache clean
  - npm install
  - npm install -g hexo-cli
  - npm install -- save-dev hexo-util
  - npm install --save hexo-tag-aplayer

build_script:
  - hexo generate

artifacts:
  - path: public

on_success:
  - echo 'hello,let us do something'
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "%GIT_USER_EMAIL%"
  - git config --global user.name "%GIT_USER_NAME%"
  - git clone --depth 5 -q --branch=%TARGET_BRANCH% %STATIC_SITE_REPO% %TEMP%\static-site
  - cd %TEMP%\static-site
  - del * /f /q
  - for /d %%p IN (*) do rmdir "%%p" /s /q
  - SETLOCAL EnableDelayedExpansion & robocopy "%APPVEYOR_BUILD_FOLDER%\public" "%TEMP%\static-site" /e & IF !ERRORLEVEL! EQU 1 (exit 0) ELSE (IF !ERRORLEVEL! EQU 3 (exit 0) ELSE (exit 1))
  - git add -A
  - if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER (git diff --quiet --exit-code --cached || git commit -m "Update Static Site" && git push origin %TARGET_BRANCH% && appveyor AddMessage "Static Site Updated")
